### ISSUE TITLE
transformable convex polyhedrons

### ISSUE THREAD

**Issue by expenses** [rustgd/collision-rs#102]
Hi, I'm currently using convex polyhedrons for ray casting so i can select objects by clicking on them etc. Unfortunately, there doesn't seem to be any way to take an existing polyhedron and translate/rotate/scale it, which means i have to create it from scratch each time, which consumes a lot of cpu per frame. I could try translating the ray around the polyhedron instead so I can just build it once, but this sounds like a roundabout way when it should be possible to just transform the existing polyhedron. I'll look into the source code and try implement this myself.

**Comment by Rhuagh** [comment]
You can use the `ContinuousTransformed` functionality instead of `Continuous` for the ray casting.

`poly.intersects_transformed(ray, transform)`

**Comment by Rhuagh** [comment]
https://docs.rs/collision/0.18.0/collision/trait.ContinuousTransformed.html

**Comment by expenses** [comment]
@Rhuagh oh, excellent, thats exactly what I want!
