### ISSUE TITLE
collision-rs out of sync with cgmath

### ISSUE THREAD

**Issue by trsoluti** [rustgd/collision-rs#108]
Here's a strange problem that cost me an afternoon:

1. collision-rs currently relies on cgmath version 0.16. cgmath is now at 0.17.
2. collision-rs structures refer to cgmath structures such as Point2.

If I compile a program with the latest collision-rs and the latest cgmath, I get the following error message on my types:

`the trait EuclideanSpace is not implemented for cgmath::point::Point2<f32>`

(This is for the constraint `P::Point: EuclideanSpace`, which is used by amethyst-rhusics.)

Here is a simple snippet that reproduces the problem:
```rust
use cgmath::EuclideanSpace;
use collision::Primitive;
use collision::primitive::Primitive2;

fn main() {
    do_it::<Primitive2<f32>>();
}

fn do_it<P>()
where
    P: Primitive,
    P::Point: EuclideanSpace,
{
    println!("hello!")
}
```

It seems as if you need a crate-version of collision-rs for every crate-version of cgmath, so a user can pick the right pair.

**Comment by kvark** [comment]
Another way to get us stable across `cgmath` releases is #10
cc @vitvakatu

**Comment by vitvakatu** [comment]
Unfortunately I'm unable to find some time to work on this right now, so hopping anyone else will do.

**Comment by trsoluti** [comment]
I've created a sync'd version of collision-rs in my folder [https://github.com/trsoluti/collision-rs](https://github.com/trsoluti/collision-rs) that also has been updated to rust-2018 and reduces some of the double-dependencies (e.g. uses traits re-exported from cgmath instead of importing them directly from the source library). It solves my test case.

Someone please take a look at it, see if it's okay, and guide me through the pull request process. Thanks in advance.

**Comment by kvark** [comment]
@trsoluti please file a PR right away for the review, it doesn't have to be perfect ;)

**Comment by trsoluti** [comment]
The updated collision-rs is still not on Crates.io. How to push it? (I want to update rhusics next.)

**Comment by kvark** [comment]
Sorry about the delay!
https://crates.io/crates/collision/0.20.1
