### ISSUE TITLE
Contains implementation for Aabb/Point is unsafe for unsigned BaseNums

### ISSUE THREAD

**Issue by spearman** [rustgd/collision-rs#53]
The current implementation uses subtracts and then checks the result. This will cause 'subtract with overflow' panic for points outside the aabb (both 2d and 3d use this method).

Shouldn't it simply be a one-liner:

    min_x <= x && x <= max_x && min_y <= y && y <= max_y && min_z <= z && z <= max_z

?

**Comment by kvark** [comment]
Nicely spotted!

**Comment by spearman** [comment]
So according to this test an Aabb should not contain its own max(), is that intentional?

https://github.com/kvark/collision-rs/blob/f69b098c233836615cf3d47e5b65666664582153/tests/aabb.rs#L66

If so it would end up looking something like:

    min_x <= x && x < max_x && min_y <= y && y < max_y && min_z <= z && z < max_z

**Comment by Rhuagh** [comment]
We have yet to define border semantics, for the most part I think border tests are misses
