### ISSUE TITLE
Rect and Cube support

### ISSUE THREAD

**Issue by SirVer** [rustgd/collision-rs#73]
I am working a lot with [octrees and quadtrees these days](https://github.com/googlecartographer/point_cloud_viewer). I am using collision-rs for bounds checking and for the `Aabb` types and traits. Great work!

However, I often want to encode the invariant that a `Aabb2` is actually a `Square` and that an `Aabb3` is actually a `Cube`, i.e. I want to make the state unpresentable that their edge lengths vary. For this I added my own [tiny implementation of these types](https://github.com/googlecartographer/point_cloud_viewer/blob/master/src/math.rs#L32). 

I wonder if there is interest to upstream these types into this crate and how they would be best implemented/designed for collision?

Edit: Replace Rectangle through Square.

**Comment by Rhuagh** [comment]
Well, there's the `Cuboid` and `Rectangle` primitives already. Not sure these actually add much value?

**Comment by SirVer** [comment]
Those primitives reperesent n-dimensional boxes that might have different edge length in all directions. In my case that is precisely what I do not want. I want to encode that my primitives have the same edge length in all directions and I want to encode this as a hard invariant of my type. Hence Cube and Square.

**Comment by Rhuagh** [comment]
True. There's some merit to the idea, but I'm a bit hesitant to adding what will essentially be duplicated code with an extra invariant.

**Comment by SirVer** [comment]
That is a valid trade-off to decide on. For my code I definitely liked the invariant, but as a maintainer you'll need to care for the extra code. I am perfectly fine with this being closed as out of scope.
